# Generated by Django 5.1.3 on 2024-11-13 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPLPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('ipl_id', models.CharField(max_length=50, null=True, unique=True)),
                ('nationality', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('role', models.CharField(choices=[('BAT', 'Batsman'), ('BOWL', 'Bowler'), ('ALL', 'All-Rounder'), ('WK', 'Wicket Keeper')], max_length=4)),
                ('batting_style', models.CharField(choices=[('RIGHT', 'Right Handed'), ('LEFT', 'Left Handed')], max_length=5)),
                ('bowling_style', models.CharField(choices=[('FAST', 'Fast'), ('MED_FAST', 'Medium Fast'), ('MEDIUM', 'Medium'), ('SPIN', 'Spin'), ('NA', 'Not Applicable')], default='NA', max_length=10)),
                ('img', models.ImageField(blank=True, null=True, upload_to='players/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IPLTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=5)),
                ('home_ground', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('primary_color', models.CharField(max_length=7)),
                ('secondary_color', models.CharField(max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ipl_teams/')),
                ('other_names', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerTeamHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.iplplayer')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.iplteam')),
            ],
            options={
                'ordering': ['-season__year'],
            },
        ),
        migrations.AddField(
            model_name='iplplayer',
            name='teams',
            field=models.ManyToManyField(related_name='players', through='api.PlayerTeamHistory', to='api.iplteam'),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=20)),
            ],
            options={
                'ordering': ['-year'],
                'indexes': [models.Index(fields=['status'], name='api_season_status_6611d0_idx'), models.Index(fields=['start_date'], name='api_season_start_d_5864c9_idx')],
            },
        ),
        migrations.AddField(
            model_name='playerteamhistory',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.season'),
        ),
        migrations.CreateModel(
            name='IPLMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_number', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ABANDONED', 'Abandoned')], default='SCHEDULED', max_length=10)),
                ('toss_decision', models.CharField(choices=[('BAT', 'Bat'), ('BOWL', 'Bowl')], max_length=4, null=True)),
                ('win_margin', models.IntegerField(null=True)),
                ('win_type', models.CharField(max_length=50, null=True)),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='api.iplteam')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='api.iplteam')),
                ('toss_winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toss_wins', to='api.iplteam')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_wins', to='api.iplteam')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.season')),
            ],
            options={
                'ordering': ['season', 'match_number'],
            },
        ),
        migrations.CreateModel(
            name='TeamSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_ground', models.CharField(max_length=100)),
                ('captain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_of', to='api.iplplayer')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.iplteam')),
            ],
        ),
        migrations.AddField(
            model_name='iplteam',
            name='seasons',
            field=models.ManyToManyField(related_name='teams', through='api.TeamSeason', to='api.season'),
        ),
        migrations.AddIndex(
            model_name='iplplayer',
            index=models.Index(fields=['role'], name='api_iplplay_role_cd8b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='iplplayer',
            index=models.Index(fields=['is_active'], name='api_iplplay_is_acti_ecdd3a_idx'),
        ),
        migrations.AddIndex(
            model_name='iplplayer',
            index=models.Index(fields=['nationality'], name='api_iplplay_nationa_cf443a_idx'),
        ),
        migrations.AddIndex(
            model_name='playerteamhistory',
            index=models.Index(fields=['player', 'season'], name='api_playert_player__6fc219_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playerteamhistory',
            unique_together={('player', 'season')},
        ),
        migrations.AddIndex(
            model_name='iplmatch',
            index=models.Index(fields=['date'], name='api_iplmatc_date_48db17_idx'),
        ),
        migrations.AddIndex(
            model_name='iplmatch',
            index=models.Index(fields=['status'], name='api_iplmatc_status_823756_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='iplmatch',
            unique_together={('season', 'match_number')},
        ),
        migrations.AlterUniqueTogether(
            name='teamseason',
            unique_together={('team', 'season')},
        ),
        migrations.AddIndex(
            model_name='iplteam',
            index=models.Index(fields=['short_name'], name='api_iplteam_short_n_eba587_idx'),
        ),
        migrations.AddIndex(
            model_name='iplteam',
            index=models.Index(fields=['is_active'], name='api_iplteam_is_acti_907904_idx'),
        ),
    ]
