# Generated by Django 5.1.3 on 2024-12-24 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iplmatch',
            name='inns_1_overs',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='iplmatch',
            name='inns_1_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='iplmatch',
            name='inns_1_wickets',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='iplmatch',
            name='inns_2_overs',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='iplmatch',
            name='inns_2_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='iplmatch',
            name='inns_2_wickets',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='iplmatch',
            name='player_of_match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_of_match', to='api.iplplayer'),
        ),
        migrations.AddField(
            model_name='iplmatch',
            name='stage',
            field=models.CharField(choices=[('LEAGUE', 'League'), ('QUALIFIER', 'Qualifier'), ('ELIMINATOR', 'Eliminator'), ('SEMI_FINAL', 'Semi Final'), ('THIRD_PLACE', 'Third Place'), ('FINAL', 'Final')], default='LEAGUE', max_length=20),
        ),
        migrations.AlterField(
            model_name='iplmatch',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='iplmatch',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('NO_RESULT', 'No Result'), ('ABANDONED', 'Abandoned')], default='SCHEDULED', max_length=10),
        ),
        migrations.AlterField(
            model_name='iplmatch',
            name='win_type',
            field=models.CharField(choices=[('RUNS', 'Runs'), ('WICKETS', 'Wickets'), ('TIE', 'Tie'), ('SUPER_OVER', 'Super Over'), ('NO_RESULT', 'No Result')], max_length=10, null=True),
        ),
    ]
