# Generated by Django 5.1.3 on 2024-12-24 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_price_playerteamhistory_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplmatch',
            name='inns_1_overs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iplmatch',
            name='inns_1_runs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iplmatch',
            name='inns_1_wickets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iplmatch',
            name='inns_2_overs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iplmatch',
            name='inns_2_runs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iplmatch',
            name='inns_2_wickets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iplmatch',
            name='player_of_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_of_match', to='api.iplplayer'),
        ),
        migrations.AlterField(
            model_name='iplmatch',
            name='toss_decision',
            field=models.CharField(blank=True, choices=[('BAT', 'Bat'), ('BOWL', 'Bowl')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='iplmatch',
            name='toss_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toss_wins', to='api.iplteam'),
        ),
        migrations.AlterField(
            model_name='iplmatch',
            name='win_type',
            field=models.CharField(blank=True, choices=[('RUNS', 'Runs'), ('WICKETS', 'Wickets'), ('TIE', 'Tie'), ('SUPER_OVER', 'Super Over'), ('NO_RESULT', 'No Result')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='iplmatch',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_wins', to='api.iplteam'),
        ),
    ]
