# Generated by Django 5.1.3 on 2024-12-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_playerteamhistory_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerteamhistory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='teamseason',
            name='captain',
        ),
        migrations.RemoveField(
            model_name='teamseason',
            name='home_ground',
        ),
        migrations.AddField(
            model_name='playerteamhistory',
            name='points',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
