# Generated by Django 5.1.3 on 2024-12-26 01:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_playerteamhistory_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPLPlayerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bat_runs', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bat_balls', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bat_fours', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bat_sixes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bat_not_out', models.BooleanField(default=False)),
                ('bat_innings', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bowl_balls', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bowl_maidens', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bowl_runs', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bowl_wickets', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bowl_innings', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('field_catch', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('wk_catch', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('wk_stumping', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('run_out_solo', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('run_out_collab', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('player_of_match', models.BooleanField(default=False)),
                ('for_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_events', to='api.iplteam')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.iplmatch')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.iplplayer')),
                ('vs_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_events', to='api.iplteam')),
            ],
            options={
                'indexes': [models.Index(fields=['player', 'match'], name='api_iplplay_player__6e202d_idx'), models.Index(fields=['for_team', 'vs_team'], name='api_iplplay_for_tea_a19bdd_idx')],
            },
        ),
    ]
