# Generated by Django 5.1.3 on 2024-12-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_iplplayerevent_bat_balls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplplayerevent',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
