# Generated by Django 5.1.3 on 2024-12-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_iplplayerevent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplplayerevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
