# Generated by Django 5.1.3 on 2024-12-28 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_iplplayerevent_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='league_logos/')),
                ('color', models.CharField(max_length=7)),
                ('max_teams', models.IntegerField(default=10)),
                ('trading_enabled', models.BooleanField(default=True)),
                ('pre_season_draft_date', models.DateTimeField(blank=True, null=True)),
                ('mid_season_draft_date', models.DateTimeField(blank=True, null=True)),
                ('season_started', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_leagues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FantasyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('color', models.CharField(max_length=7)),
                ('total_points', models.IntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='api.fantasyleague')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='fantasyleague',
            index=models.Index(fields=['admin'], name='api_fantasy_admin_i_d268de_idx'),
        ),
        migrations.AddIndex(
            model_name='fantasyleague',
            index=models.Index(fields=['season_started'], name='api_fantasy_season__e1d041_idx'),
        ),
        migrations.AddIndex(
            model_name='fantasyteam',
            index=models.Index(fields=['user'], name='api_fantasy_user_id_09b6b5_idx'),
        ),
        migrations.AddIndex(
            model_name='fantasyteam',
            index=models.Index(fields=['league'], name='api_fantasy_league__2ca4ee_idx'),
        ),
        migrations.AddIndex(
            model_name='fantasyteam',
            index=models.Index(fields=['total_points'], name='api_fantasy_total_p_a98cbe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fantasyteam',
            unique_together={('user', 'league')},
        ),
    ]
