# Generated by Django 5.1.3 on 2025-01-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_fantasyleague_fantasyteam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iplplayer',
            name='ipl_id',
        ),
        migrations.AlterField(
            model_name='iplplayer',
            name='batting_style',
            field=models.CharField(blank=True, choices=[('RIGHT', 'Right Handed'), ('LEFT', 'Left Handed')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='iplplayer',
            name='bowling_style',
            field=models.CharField(blank=True, choices=[('FAST', 'Fast'), ('MED_FAST', 'Medium Fast'), ('MEDIUM', 'Medium'), ('SPIN', 'Spin'), ('NA', 'Not Applicable')], default='NA', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='iplplayer',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iplplayer',
            name='role',
            field=models.CharField(blank=True, choices=[('BAT', 'Batsman'), ('BOWL', 'Bowler'), ('ALL', 'All-Rounder'), ('WK', 'Wicket Keeper')], max_length=4, null=True),
        ),
    ]
