# Generated by Django 5.1.3 on 2025-01-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_iplplayer_ipl_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplplayer',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
