# Generated by Django 5.1.3 on 2025-01-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_iplplayer_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplplayer',
            name='role',
            field=models.CharField(blank=True, choices=[('BAT', 'Batter'), ('BOWL', 'Bowler'), ('ALL', 'All-Rounder'), ('WK', 'Wicket Keeper')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='playerteamhistory',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
