# Generated by Django 5.1.3 on 2025-01-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_iplplayer_role_alter_playerteamhistory_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='iplplayerevent',
            name='batting_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='iplplayerevent',
            name='bowling_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='iplplayerevent',
            name='fielding_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='iplplayerevent',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
