# Generated by Django 5.1.3 on 2025-01-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_iplplayerevent_batting_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iplplayerevent',
            old_name='batting_points',
            new_name='batting_points_total',
        ),
        migrations.RenameField(
            model_name='iplplayerevent',
            old_name='bowling_points',
            new_name='bowling_points_total',
        ),
        migrations.RenameField(
            model_name='iplplayerevent',
            old_name='fielding_points',
            new_name='fielding_points_total',
        ),
        migrations.RenameField(
            model_name='iplplayerevent',
            old_name='total_points',
            new_name='other_points_total',
        ),
        migrations.AddField(
            model_name='iplplayerevent',
            name='total_points_all',
            field=models.IntegerField(default=0),
        ),
    ]
