# Generated by Django 5.1.3 on 2025-01-27 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_batting_points_iplplayerevent_batting_points_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fantasyleague',
            name='api_fantasy_season__e1d041_idx',
        ),
        migrations.RemoveField(
            model_name='fantasyleague',
            name='mid_season_draft_date',
        ),
        migrations.RemoveField(
            model_name='fantasyleague',
            name='pre_season_draft_date',
        ),
        migrations.RemoveField(
            model_name='fantasyleague',
            name='season_started',
        ),
        migrations.RemoveField(
            model_name='fantasyleague',
            name='trading_enabled',
        ),
        migrations.AddField(
            model_name='fantasyleague',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.season'),
        ),
        migrations.AddIndex(
            model_name='fantasyleague',
            index=models.Index(fields=['season'], name='api_fantasy_season__6d3ff6_idx'),
        ),
    ]
