# Generated by Django 5.1.3 on 2025-02-01 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_fantasyleague_api_fantasy_season__e1d041_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FantasyTeam',
            new_name='FantasySquad',
        ),
        migrations.RenameIndex(
            model_name='fantasysquad',
            new_name='api_fantasy_user_id_09a2fd_idx',
            old_name='api_fantasy_user_id_09b6b5_idx',
        ),
        migrations.RenameIndex(
            model_name='fantasysquad',
            new_name='api_fantasy_league__cec761_idx',
            old_name='api_fantasy_league__2ca4ee_idx',
        ),
        migrations.RenameIndex(
            model_name='fantasysquad',
            new_name='api_fantasy_total_p_8e33bf_idx',
            old_name='api_fantasy_total_p_a98cbe_idx',
        ),
        migrations.AddField(
            model_name='fantasyleague',
            name='league_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
