# Generated by Django 5.1.3 on 2025-02-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_fantasyteam_fantasysquad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyleague',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
