# Generated by Django 5.1.3 on 2025-02-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyleague',
            name='draft_completed',
            field=models.BooleanField(default=False),
        ),
    ]
