# Generated by Django 5.1.3 on 2025-02-03 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_fantasydraftorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FantasyDraftOrder',
            new_name='FantasyDraft',
        ),
        migrations.RenameIndex(
            model_name='fantasydraft',
            new_name='api_fantasy_league__506e85_idx',
            old_name='api_fantasy_league__a5eb74_idx',
        ),
        migrations.RenameIndex(
            model_name='fantasydraft',
            new_name='api_fantasy_squad_i_e5ac9c_idx',
            old_name='api_fantasy_squad_i_a037b6_idx',
        ),
        migrations.RenameIndex(
            model_name='fantasydraft',
            new_name='api_fantasy_type_0036b8_idx',
            old_name='api_fantasy_type_5cb06b_idx',
        ),
    ]
