# Generated by Django 5.1.3 on 2025-02-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_fantasydraftorder_fantasydraft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='default_draft_order',
            field=models.JSONField(default=list),
        ),
    ]
