# Generated by Django 5.1.3 on 2025-02-07 22:16

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_season_default_draft_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyBoostRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('role', multiselectfield.db.fields.MultiSelectField(choices=[('BAT', 'Batter'), ('BOWL', 'Bowler'), ('ALL', 'All-Rounder'), ('WK', 'Wicket Keeper')], max_length=50)),
                ('multiplier_runs', models.FloatField(choices=[(1.0, '1x'), (1.5, '1.5x'), (2.0, '2x')])),
                ('multiplier_fours', models.FloatField(choices=[(1.0, '1x'), (1.5, '1.5x'), (2.0, '2x')])),
                ('multiplier_sixes', models.FloatField(choices=[(1.0, '1x'), (1.5, '1.5x'), (2.0, '2x')])),
                ('multiplier_sr', models.FloatField(choices=[(1.0, '1x'), (1.5, '1.5x'), (2.0, '2x')])),
                ('multiplier_bat_milestones', models.FloatField(choices=[(1.0, '1x'), (1.5, '1.5x'), (2.0, '2x')])),
                ('multiplier_wickets', models.FloatField(choices=[(1.0, '1x'), (1.5, '1.5x'), (2.0, '2x')])),
                ('multiplier_maidens', models.FloatField(choices=[(1.0, '1x'), (1.5, '1.5x'), (2.0, '2x')])),
                ('multiplier_economy', models.FloatField(choices=[(1.0, '1x'), (1.5, '1.5x'), (2.0, '2x')])),
                ('multiplier_bowl_milestones', models.FloatField(choices=[(1.0, '1x'), (1.5, '1.5x'), (2.0, '2x')])),
                ('multiplier_catches', models.FloatField(choices=[(1.0, '1x'), (1.5, '1.5x'), (2.0, '2x')])),
                ('multiplier_stumpings', models.FloatField(choices=[(1.0, '1x'), (1.5, '1.5x'), (2.0, '2x')])),
                ('multiplier_run_outs', models.FloatField(choices=[(1.0, '1x'), (1.5, '1.5x'), (2.0, '2x')])),
                ('multiplier_potm', models.FloatField(choices=[(1.0, '1x'), (1.5, '1.5x'), (2.0, '2x')])),
                ('multiplier_playing', models.FloatField(choices=[(1.0, '1x'), (1.5, '1.5x'), (2.0, '2x')])),
            ],
            options={
                'indexes': [models.Index(fields=['role'], name='api_fantasy_role_38c9ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='FantasyPlayerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.FloatField(default=0)),
                ('boost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fantasyboostrole')),
                ('fantasy_squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_events', to='api.fantasysquad')),
                ('match_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.iplplayerevent')),
            ],
            options={
                'indexes': [models.Index(fields=['match_event'], name='api_fantasy_match_e_16cab2_idx'), models.Index(fields=['fantasy_squad'], name='api_fantasy_fantasy_ac145a_idx'), models.Index(fields=['total_points'], name='api_fantasy_total_p_5bf509_idx')],
            },
        ),
    ]
