# Generated by Django 5.1.3 on 2025-02-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_fantasyboostrole_fantasyplayerevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasysquad',
            name='current_squad',
            field=models.JSONField(default=list),
        ),
    ]
