# Generated by Django 5.1.3 on 2025-02-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_fantasysquad_current_squad'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasysquad',
            name='core_squad',
            field=models.JSONField(default=list),
        ),
    ]
