# Generated by Django 5.1.3 on 2025-02-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_fantasysquad_core_squad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fantasysquad',
            name='core_squad',
        ),
        migrations.AddField(
            model_name='fantasysquad',
            name='current_core_squad',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='fantasysquad',
            name='future_core_squad',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='fantasysquad',
            name='current_squad',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
