# Generated by Django 5.1.3 on 2025-02-09 02:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_fantasysquad_core_squad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasysquad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fantasysquad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
