# Generated by Django 5.1.3 on 2025-02-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_fantasysquad_created_at_fantasysquad_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplmatch',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
