# Generated by Django 5.1.3 on 2025-02-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_iplmatch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='iplplayer',
            name='cricdata_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
