# Generated by Django 5.1.3 on 2025-02-17 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_iplmatch_cricdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplmatch',
            name='team_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='api.iplteam'),
        ),
        migrations.AlterField(
            model_name='iplmatch',
            name='team_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='api.iplteam'),
        ),
    ]
