# Generated by Django 5.1.3 on 2025-02-25 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_iplmatch_team_1_alter_iplmatch_team_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players_given', models.JSONField(blank=True, default=list, null=True)),
                ('players_received', models.JSONField(blank=True, default=list, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Closed', 'Closed')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('initator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_trades', to='api.fantasysquad')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_trades', to='api.fantasysquad')),
            ],
        ),
    ]
