# Generated by Django 5.1.3 on 2025-02-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_fantasytrade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fantasytrade',
            old_name='initator',
            new_name='initiator',
        ),
        migrations.AddIndex(
            model_name='fantasytrade',
            index=models.Index(fields=['initiator'], name='api_fantasy_initiat_10be11_idx'),
        ),
        migrations.AddIndex(
            model_name='fantasytrade',
            index=models.Index(fields=['receiver'], name='api_fantasy_receive_b3894c_idx'),
        ),
        migrations.AddIndex(
            model_name='fantasytrade',
            index=models.Index(fields=['status'], name='api_fantasy_status_4e051e_idx'),
        ),
    ]
