# Generated by Django 5.1.3 on 2025-02-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_rename_initator_fantasytrade_initiator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasytrade',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Closed', 'Closed')], default='Pending', max_length=10),
        ),
    ]
