# Generated by Django 5.1.3 on 2025-03-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_fantasytrade_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fantasyplayerevent',
            name='api_fantasy_total_p_5bf509_idx',
        ),
        migrations.RenameField(
            model_name='fantasyplayerevent',
            old_name='total_points',
            new_name='boost_points',
        ),
        migrations.AddIndex(
            model_name='fantasyplayerevent',
            index=models.Index(fields=['boost_points'], name='api_fantasy_boost_p_ff29d3_idx'),
        ),
    ]
