# Generated by Django 5.1.3 on 2025-03-08 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_fantasyplayerevent_api_fantasy_total_p_5bf509_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasyplayerevent',
            name='boost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fantasyboostrole'),
        ),
    ]
