# Generated by Django 5.1.3 on 2025-03-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_fantasyplayerevent_boost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasysquad',
            name='total_points',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
