# Generated by Django 5.1.3 on 2025-03-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_fantasysquad_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyleague',
            name='snake_draft_order',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
