# Generated by Django 5.1.3 on 2025-03-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_fantasyleague_snake_draft_order'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='iplmatch',
        #     name='phase',
        #     field=models.IntegerField(default=1),
        # ),
    ]
