# Generated by Django 5.1.3 on 2025-03-30 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_fix_postgres_compatibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyMatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_base_points', models.FloatField(default=0)),
                ('total_boost_points', models.FloatField(default=0)),
                ('total_points', models.FloatField(default=0)),
                ('match_rank', models.IntegerField(blank=True, null=True)),
                ('running_rank', models.IntegerField(blank=True, null=True)),
                ('running_total_points', models.FloatField(default=0)),
                ('players_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fantasy_squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to='api.fantasysquad')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.iplmatch')),
            ],
            options={
                'indexes': [models.Index(fields=['match', 'total_points'], name='api_fantasy_match_i_e97362_idx'), models.Index(fields=['fantasy_squad', 'match'], name='api_fantasy_fantasy_bb9d6d_idx'), models.Index(fields=['fantasy_squad', 'running_rank'], name='api_fantasy_fantasy_478b51_idx'), models.Index(fields=['match', 'match_rank'], name='api_fantasy_match_i_0cd972_idx')],
                'unique_together': {('match', 'fantasy_squad')},
            },
        ),
    ]
