# Generated by Django 5.1.3 on 2025-04-06 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_iplmatch_phase_fantasymatchevent'),
        ('api', 'optimize_iplplaerevent_indexes'),
    ]

    operations = [
    ]
