# Generated by Django 5.1.3 on 2025-04-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_add_simple_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyleague',
            name='draft_pool',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
