# Generated by Django 5.1.3 on 2025-05-07 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_fantasyleague_draft_pool_iplmatch_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('match_details', models.JSONField(default=dict)),
                ('player_details', models.JSONField(default=dict)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='api.fantasyleague')),
            ],
        ),
    ]
