# Generated by Codex on 2026-01-12

import django.db.models.deletion
from django.db import migrations, models


def create_default_competition(apps, schema_editor):
    Competition = apps.get_model('api', 'Competition')
    Season = apps.get_model('api', 'Season')

    competition, _ = Competition.objects.get_or_create(
        name='Indian Premier League',
        defaults={
            'format': 'T20',
            'grade': 'FRANCHISE',
        },
    )

    Season.objects.filter(competition__isnull=True).update(competition=competition)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_iplmatch_phase_fantasystats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('format', models.CharField(choices=[('T20', 'T20'), ('ODI', 'ODI'), ('TEST', 'Test')], max_length=10)),
                ('grade', models.CharField(choices=[('DOMESTIC', 'Domestic'), ('FRANCHISE', 'Franchise'), ('INTERNATIONAL', 'International')], max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['format'], name='competition_format_idx'), models.Index(fields=['grade'], name='competition_grade_idx')],
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='season',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='api.competition'),
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='SeasonPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=100)),
                ('open_at', models.DateTimeField()),
                ('lock_at', models.DateTimeField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='api.season')),
            ],
            options={
                'ordering': ['season_id', 'phase'],
                'unique_together': {('season', 'phase')},
            },
        ),
        migrations.CreateModel(
            name='DraftWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('PRE_SEASON', 'Pre-Season'), ('MID_SEASON', 'Mid-Season'), ('PLAYOFF', 'Playoff'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=20)),
                ('sequence', models.PositiveIntegerField()),
                ('open_at', models.DateTimeField()),
                ('lock_at', models.DateTimeField()),
                ('retention_phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_windows', to='api.seasonphase')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_windows', to='api.season')),
            ],
            options={
                'ordering': ['season_id', 'sequence'],
                'unique_together': {('season', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='SquadPhaseBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignments', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fantasy_squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_boosts', to='api.fantasysquad')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_boosts', to='api.seasonphase')),
            ],
            options={
                'ordering': ['phase_id', 'fantasy_squad_id'],
                'unique_together': {('fantasy_squad', 'phase')},
            },
        ),
        migrations.AddField(
            model_name='fantasydraft',
            name='draft_window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='api.draftwindow'),
        ),
        migrations.RunPython(create_default_competition, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('competition', 'year'), name='uniq_competition_year'),
        ),
    ]
