# Generated by Codex on 2026-01-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_competitions_phases_drafts'),
    ]

    operations = [
        migrations.AddField(
            model_name='iplmatch',
            name='season_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='api.seasonphase'),
        ),
    ]
