# Generated by Codex on 2026-01-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_iplmatch_season_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftwindow',
            name='draft_pool',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
