# Generated by Django 5.1.3 on 2026-02-05 00:23

import django.db.models.deletion
from django.db import migrations, models


def assign_default_competition(apps, schema_editor):
    Competition = apps.get_model('api', 'Competition')
    Season = apps.get_model('api', 'Season')

    fallback_competition, _ = Competition.objects.get_or_create(
        name='Unassigned Competition',
        defaults={
            'format': 'T20',
            'grade': 'DOMESTIC',
        },
    )
    Season.objects.filter(competition__isnull=True).update(competition=fallback_competition)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_draftwindow_pool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.iplmatch',),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.iplplayer',),
        ),
        migrations.CreateModel(
            name='PlayerMatchEvent',
            fields=[
            ],
            options={
                'verbose_name': 'Player Match Event',
                'verbose_name_plural': 'Player Match Events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.iplplayerevent',),
        ),
        migrations.CreateModel(
            name='PlayerSeasonTeam',
            fields=[
            ],
            options={
                'verbose_name': 'Player Season Team',
                'verbose_name_plural': 'Player Season Teams',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.playerteamhistory',),
        ),
        migrations.CreateModel(
            name='SeasonTeam',
            fields=[
            ],
            options={
                'verbose_name': 'Season Team',
                'verbose_name_plural': 'Season Teams',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.teamseason',),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.iplteam',),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='iplmatch',
                    name='phase',
                    field=models.IntegerField(default=1),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "api_iplmatch" '
                        'ADD COLUMN IF NOT EXISTS "phase" integer DEFAULT 1 NOT NULL;'
                        'ALTER TABLE "api_iplmatch" ALTER COLUMN "phase" DROP DEFAULT;'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.RunPython(assign_default_competition, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='season',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='api.competition'),
        ),
        migrations.CreateModel(
            name='CompetitionTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='api.competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_memberships', to='api.iplteam')),
            ],
            options={
                'ordering': ['competition__name', 'team__name'],
            },
        ),
        migrations.AddField(
            model_name='iplteam',
            name='competitions',
            field=models.ManyToManyField(blank=True, related_name='registered_teams', through='api.CompetitionTeam', to='api.competition'),
        ),
        migrations.AddIndex(
            model_name='competitionteam',
            index=models.Index(fields=['competition', 'team'], name='api_competi_competi_a3a4e9_idx'),
        ),
        migrations.AddIndex(
            model_name='competitionteam',
            index=models.Index(fields=['team'], name='api_competi_team_id_d7f355_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='competitionteam',
            unique_together={('competition', 'team')},
        ),
    ]
