# Generated by Codex on 2026-02-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_match_player_playermatchevent_playerseasonteam_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name='Match'),
                migrations.DeleteModel(name='Player'),
                migrations.DeleteModel(name='PlayerMatchEvent'),
                migrations.DeleteModel(name='PlayerSeasonTeam'),
                migrations.DeleteModel(name='SeasonTeam'),
                migrations.DeleteModel(name='Team'),
                migrations.RenameModel(old_name='IPLTeam', new_name='Team'),
                migrations.RenameModel(old_name='TeamSeason', new_name='SeasonTeam'),
                migrations.RenameModel(old_name='IPLPlayer', new_name='Player'),
                migrations.RenameModel(old_name='PlayerTeamHistory', new_name='PlayerSeasonTeam'),
                migrations.RenameModel(old_name='IPLMatch', new_name='Match'),
                migrations.RenameModel(old_name='IPLPlayerEvent', new_name='PlayerMatchEvent'),
                migrations.AlterModelTable(name='Team', table='api_iplteam'),
                migrations.AlterModelTable(name='SeasonTeam', table='api_teamseason'),
                migrations.AlterModelTable(name='Player', table='api_iplplayer'),
                migrations.AlterModelTable(name='PlayerSeasonTeam', table='api_playerteamhistory'),
                migrations.AlterModelTable(name='Match', table='api_iplmatch'),
                migrations.AlterModelTable(name='PlayerMatchEvent', table='api_iplplayerevent'),
            ],
        ),
    ]
