# Generated by Codex on 2026-02-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_rename_ipl_models_to_generic_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasydraft',
            name='role',
            field=models.CharField(
                blank=True,
                choices=[
                    ('BAT', 'Batter'),
                    ('WK', 'Wicket Keeper'),
                    ('ALL', 'All-Rounder'),
                    ('BOWL', 'Bowler'),
                ],
                max_length=4,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name='fantasydraft',
            index=models.Index(
                fields=['league', 'type', 'role'],
                name='api_fantdraft_ltr_idx',
            ),
        ),
    ]
