# Generated by Codex on 2026-02-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_fantasydraft_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='sportmonk_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='sportmonk_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='sportmonk_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
