# Generated by Django 5.1.3 on 2026-02-19 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_add_sportmonk_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerseasonteam',
            name='replacement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_player_season_teams', to='api.player'),
        ),
        migrations.AddField(
            model_name='playerseasonteam',
            name='ruled_out',
            field=models.BooleanField(default=False),
        ),
    ]
