# Generated by Django 5.1.3 on 2026-02-19 19:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_playerseasonteam_ruled_out_replacement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftWindowLeagueRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dry_run', models.BooleanField(default=False)),
                ('standings_snapshot', models.JSONField(blank=True, default=list)),
                ('snake_order_by_role', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='DraftWindowTeamEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_remaining', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['draft_window_id', 'season_team_id'],
            },
        ),
        migrations.AddField(
            model_name='draftwindow',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftwindow',
            name='pool_compiled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftwindow',
            name='retention_mode',
            field=models.CharField(choices=[('AUTO_NEXT_PHASE_AFTER_LOCK', 'Auto: Next Phase After Lock'), ('MANUAL_PHASE', 'Manual Phase')], default='AUTO_NEXT_PHASE_AFTER_LOCK', max_length=40),
        ),
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('LEAGUE', 'League'), ('GROUP', 'Group'), ('SUPER_SIXES', 'Super Sixes'), ('SUPER_EIGHTS', 'Super Eights'), ('QUALIFIER', 'Qualifier'), ('ELIMINATOR', 'Eliminator'), ('SEMI_FINAL', 'Semi Final'), ('THIRD_PLACE', 'Third Place'), ('FINAL', 'Final')], default='LEAGUE', max_length=20),
        ),
        migrations.AddField(
            model_name='draftwindowleaguerun',
            name='draft_window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_runs', to='api.draftwindow'),
        ),
        migrations.AddField(
            model_name='draftwindowleaguerun',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_window_executions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='draftwindowleaguerun',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_window_runs', to='api.fantasyleague'),
        ),
        migrations.AddField(
            model_name='draftwindowteameligibility',
            name='draft_window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_eligibility', to='api.draftwindow'),
        ),
        migrations.AddField(
            model_name='draftwindowteameligibility',
            name='season_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_window_eligibility', to='api.seasonteam'),
        ),
        migrations.AddIndex(
            model_name='draftwindowleaguerun',
            index=models.Index(fields=['draft_window', 'league'], name='api_draftwi_draft_w_983650_idx'),
        ),
        migrations.AddIndex(
            model_name='draftwindowleaguerun',
            index=models.Index(fields=['league'], name='api_draftwi_league__153add_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='draftwindowleaguerun',
            unique_together={('draft_window', 'league')},
        ),
        migrations.AddIndex(
            model_name='draftwindowteameligibility',
            index=models.Index(fields=['draft_window', 'is_remaining'], name='api_draftwi_draft_w_aa452a_idx'),
        ),
        migrations.AddIndex(
            model_name='draftwindowteameligibility',
            index=models.Index(fields=['season_team'], name='api_draftwi_season__507392_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='draftwindowteameligibility',
            unique_together={('draft_window', 'season_team')},
        ),
    ]
